export const overviewKPIs = [
  { label: "Registered Users", value: 1284, delta: "+12.4%", trend: "up", icon: "Users" },
  { label: "Active Users", value: 342, delta: "+3.1%", trend: "up", icon: "UserCheck" },
  { label: "Active Sessions", value: 47, delta: "+8", trend: "up", icon: "Radio" },
  { label: "Connected Cameras", value: 62, delta: "+2", trend: "up", icon: "Video" },
  { label: "AI Models Loaded", value: 4, delta: "stable", trend: "flat", icon: "Cpu" },
  { label: "Total Reports", value: 8921, delta: "+184", trend: "up", icon: "FileText" },
  { label: "Alerts Today", value: 128, delta: "-6.2%", trend: "down", icon: "AlertTriangle" },
  { label: "System Uptime", value: "99.98%", delta: "30d", trend: "flat", icon: "Activity" },
];
export const healthServices = [
  { name: "Backend API", status: "operational", latency: "42ms", uptime: 99.99 },
  { name: "AI Inference", status: "operational", latency: "118ms", uptime: 99.94 },
  { name: "Database", status: "operational", latency: "9ms", uptime: 99.99 },
  { name: "Storage", status: "operational", latency: "24ms", uptime: 99.97 },
  { name: "API Gateway", status: "operational", latency: "18ms", uptime: 99.99 },
  { name: "WebSocket", status: "degraded", latency: "204ms", uptime: 98.72 },
  { name: "Email Service", status: "operational", latency: "312ms", uptime: 99.81 },
  { name: "WhatsApp Service", status: "operational", latency: "428ms", uptime: 99.63 },
];
export const resourceMetrics = [
  { name: "GPU", used: 68, total: 100, unit: "%", detail: "NVIDIA A10G · 21.7 / 24 GB" },
  { name: "CPU", used: 42, total: 100, unit: "%", detail: "16 vCPU · load 6.7" },
  { name: "RAM", used: 57, total: 100, unit: "%", detail: "36.4 / 64 GB" },
  { name: "Disk", used: 74, total: 100, unit: "%", detail: "740 / 1000 GB" },
];
export const users = [
  {
    id: "u_01",
    name: "Ahmad Al-Rashid",
    email: "ahmad@drivealert.ai",
    role: "Administrator",
    status: "active",
    lastLogin: "2m ago",
    sessions: 148,
    avatar: "AR",
  },
  {
    id: "u_02",
    name: "Sarah Mitchell",
    email: "sarah.m@fleet.io",
    role: "Instructor",
    status: "active",
    lastLogin: "18m ago",
    sessions: 94,
    avatar: "SM",
  },
  {
    id: "u_03",
    name: "Kenji Tanaka",
    email: "kenji@lab.jp",
    role: "Researcher",
    status: "active",
    lastLogin: "1h ago",
    sessions: 212,
    avatar: "KT",
  },
  {
    id: "u_04",
    name: "Elena Voss",
    email: "elena.v@auto.eu",
    role: "Instructor",
    status: "active",
    lastLogin: "3h ago",
    sessions: 67,
    avatar: "EV",
  },
  {
    id: "u_05",
    name: "Marcus Chen",
    email: "marcus@demo.io",
    role: "Demo User",
    status: "inactive",
    lastLogin: "2d ago",
    sessions: 4,
    avatar: "MC",
  },
  {
    id: "u_06",
    name: "Priya Anand",
    email: "priya@drivealert.ai",
    role: "Guest",
    status: "suspended",
    lastLogin: "9d ago",
    sessions: 1,
    avatar: "PA",
  },
  {
    id: "u_07",
    name: "Diego Rossi",
    email: "diego@fleetops.it",
    role: "Instructor",
    status: "active",
    lastLogin: "5h ago",
    sessions: 128,
    avatar: "DR",
  },
  {
    id: "u_08",
    name: "Nina Kowalski",
    email: "nina.k@safety.pl",
    role: "Researcher",
    status: "active",
    lastLogin: "22m ago",
    sessions: 78,
    avatar: "NK",
  },
];
export const roles = [
  {
    name: "Administrator",
    count: 4,
    color: "danger",
    permissions: 42,
    level: "Full access",
    description: "System-wide configuration and user governance.",
  },
  {
    name: "Instructor",
    count: 38,
    color: "primary",
    permissions: 24,
    level: "Elevated",
    description: "Manage drivers, sessions, and generate reports.",
  },
  {
    name: "Researcher",
    count: 21,
    color: "info",
    permissions: 18,
    level: "Data access",
    description: "Read-only analytics, exports and dataset access.",
  },
  {
    name: "Guest",
    count: 148,
    color: "muted",
    permissions: 6,
    level: "Restricted",
    description: "View shared reports and public dashboards.",
  },
  {
    name: "Demo User",
    count: 1073,
    color: "warning",
    permissions: 4,
    level: "Sandbox",
    description: "Limited sandbox with synthetic monitoring data.",
  },
];
export const activeSessions = [
  {
    id: "s_9241",
    driver: "Ahmad Al-Rashid",
    camera: "Cabin Cam · A10G-01",
    elapsed: "01:24:18",
    status: "focused",
    fatigue: 12,
    confidence: 96,
    alerts: 0,
  },
  {
    id: "s_9240",
    driver: "Sarah Mitchell",
    camera: "Cabin Cam · A10G-02",
    elapsed: "00:48:02",
    status: "warning",
    fatigue: 54,
    confidence: 91,
    alerts: 2,
  },
  {
    id: "s_9239",
    driver: "Kenji Tanaka",
    camera: "Cabin Cam · A10G-04",
    elapsed: "02:12:44",
    status: "critical",
    fatigue: 82,
    confidence: 88,
    alerts: 4,
  },
  {
    id: "s_9238",
    driver: "Elena Voss",
    camera: "Cabin Cam · A10G-03",
    elapsed: "00:22:57",
    status: "focused",
    fatigue: 18,
    confidence: 94,
    alerts: 0,
  },
  {
    id: "s_9237",
    driver: "Diego Rossi",
    camera: "Cabin Cam · A10G-07",
    elapsed: "01:05:11",
    status: "warning",
    fatigue: 46,
    confidence: 89,
    alerts: 1,
  },
  {
    id: "s_9236",
    driver: "Nina Kowalski",
    camera: "Cabin Cam · A10G-08",
    elapsed: "00:37:29",
    status: "focused",
    fatigue: 22,
    confidence: 95,
    alerts: 0,
  },
];
export const aiModels = [
  {
    name: "drowsiness-yolov8n",
    version: "v2.4.1",
    status: "active",
    accuracy: 94.7,
    map: 91.2,
    precision: 93.4,
    recall: 92.1,
    f1: 92.7,
    inference: 18,
    gpu: 4.2,
  },
  {
    name: "drowsiness-yolov8s",
    version: "v2.3.0",
    status: "standby",
    accuracy: 96.1,
    map: 93.8,
    precision: 95.2,
    recall: 94.7,
    f1: 94.9,
    inference: 34,
    gpu: 6.1,
  },
  {
    name: "eye-state-cnn",
    version: "v1.8.2",
    status: "standby",
    accuracy: 97.4,
    map: 95.6,
    precision: 97.1,
    recall: 96.9,
    f1: 97.0,
    inference: 8,
    gpu: 1.8,
  },
  {
    name: "head-pose-net",
    version: "v1.2.0",
    status: "standby",
    accuracy: 92.3,
    map: 88.4,
    precision: 91.7,
    recall: 90.4,
    f1: 91.0,
    inference: 12,
    gpu: 2.4,
  },
];
export const storageBreakdown = [
  { label: "Uploaded Videos", used: 412, unit: "GB", color: "hsl(180 65% 55%)" },
  { label: "Uploaded Images", used: 84, unit: "GB", color: "hsl(200 70% 60%)" },
  { label: "Reports", used: 26, unit: "GB", color: "hsl(160 60% 55%)" },
  { label: "Logs", used: 44, unit: "GB", color: "hsl(45 85% 60%)" },
  { label: "Temporary Files", used: 62, unit: "GB", color: "hsl(0 70% 60%)" },
  { label: "Database", used: 78, unit: "GB", color: "hsl(280 60% 65%)" },
  { label: "Backups", used: 134, unit: "GB", color: "hsl(220 60% 60%)" },
];
export const auditLogs = [
  {
    ts: "2026-07-22 09:42:18",
    user: "ahmad@drivealert.ai",
    action: "user.update",
    module: "Users",
    ip: "10.0.14.22",
    result: "success",
  },
  {
    ts: "2026-07-22 09:38:04",
    user: "sarah.m@fleet.io",
    action: "model.activate",
    module: "AI Models",
    ip: "10.0.14.87",
    result: "success",
  },
  {
    ts: "2026-07-22 09:31:57",
    user: "system",
    action: "backup.create",
    module: "Storage",
    ip: "internal",
    result: "success",
  },
  {
    ts: "2026-07-22 09:22:41",
    user: "elena.v@auto.eu",
    action: "session.stop",
    module: "Monitoring",
    ip: "10.0.15.03",
    result: "success",
  },
  {
    ts: "2026-07-22 09:14:12",
    user: "unknown",
    action: "auth.login",
    module: "Auth",
    ip: "203.0.113.44",
    result: "failed",
  },
  {
    ts: "2026-07-22 09:02:48",
    user: "kenji@lab.jp",
    action: "report.export",
    module: "Reports",
    ip: "10.0.14.61",
    result: "success",
  },
  {
    ts: "2026-07-22 08:57:29",
    user: "diego@fleetops.it",
    action: "settings.update",
    module: "Settings",
    ip: "10.0.15.18",
    result: "success",
  },
  {
    ts: "2026-07-22 08:41:03",
    user: "priya@drivealert.ai",
    action: "user.suspend",
    module: "Users",
    ip: "10.0.14.22",
    result: "success",
  },
];
export const systemLogs = [
  {
    ts: "09:42:18",
    severity: "info",
    source: "backend",
    message: "Health check passed · all services nominal",
  },
  {
    ts: "09:41:57",
    severity: "warn",
    source: "ai",
    message: "GPU memory pressure 87% on worker-a10g-04",
  },
  {
    ts: "09:41:04",
    severity: "info",
    source: "api",
    message: "POST /sessions/start · 148ms · 201",
  },
  {
    ts: "09:40:48",
    severity: "error",
    source: "notification",
    message: "WhatsApp delivery timeout for msg_29841",
  },
  {
    ts: "09:40:12",
    severity: "info",
    source: "auth",
    message: "OAuth token refreshed for user u_02",
  },
  {
    ts: "09:39:56",
    severity: "debug",
    source: "ai",
    message: "Inference batch=8 · avg 18.4ms · fps 54",
  },
  {
    ts: "09:39:22",
    severity: "info",
    source: "backend",
    message: "WebSocket peer connected · s_9241",
  },
  {
    ts: "09:38:41",
    severity: "warn",
    source: "api",
    message: "Rate limit 80% for key sk_live_***a41",
  },
  { ts: "09:38:04", severity: "info", source: "ai", message: "Model drowsiness-yolov8n activated" },
  {
    ts: "09:37:19",
    severity: "error",
    source: "backend",
    message: "DB connection retry 1/3 for pool primary",
  },
];
export const securityKPIs = [
  { label: "Failed Logins (24h)", value: 27, trend: "+4", severity: "warning" },
  { label: "Active Sessions", value: 342, trend: "+18", severity: "info" },
  { label: "Locked Accounts", value: 3, trend: "0", severity: "danger" },
  { label: "API Requests (24h)", value: "1.2M", trend: "+8%", severity: "info" },
  { label: "Security Alerts", value: 2, trend: "-1", severity: "warning" },
  { label: "Password Resets", value: 14, trend: "+2", severity: "info" },
];
export const alertTrend = Array.from({ length: 24 }, (_, i) => ({
  hour: `${String(i).padStart(2, "0")}:00`,
  alerts: Math.round(20 + Math.sin(i / 3) * 12 + Math.random() * 8),
  logins: Math.round(60 + Math.cos(i / 4) * 20 + Math.random() * 10),
}));
export const devEndpoints = [
  { label: "API Health", value: "operational", type: "status" },
  { label: "Backend Version", value: "v4.12.3", type: "text" },
  { label: "Database Version", value: "PostgreSQL 15.4", type: "text" },
  { label: "Environment", value: "production", type: "badge" },
  { label: "WebSocket Endpoint", value: "wss://api.drivealert.ai/ws", type: "code" },
  { label: "Region", value: "eu-central-1", type: "text" },
  { label: "Connected Services", value: "12 / 12", type: "text" },
  { label: "Feature Flags", value: "8 active", type: "text" },
];
