// Client for the Driver Drowsiness Detection FastAPI backend.
// Every endpoint returns { success, message, data } or
// { success: false, message, error_code, errors } - see Backend/CONTRACT.md.
import { supabase } from "@/integrations/supabase/client";

const API_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000/api/v1";

export class ApiError extends Error {
  constructor(message, { errorCode, status } = {}) {
    super(message);
    this.name = "ApiError";
    this.errorCode = errorCode;
    this.status = status;
  }
}

// Sessions/analytics/admin all require a Supabase-issued access token, which
// the backend verifies itself (app/dependencies/auth.py) rather than trusting
// Supabase's RLS - see Backend's "service-role bypasses RLS" note.
async function authFetch(path, options = {}) {
  const {
    data: { session },
  } = await supabase.auth.getSession();
  if (!session?.access_token) {
    throw new ApiError("You must be signed in to do this.", {
      errorCode: "AUTH_REQUIRED",
      status: 401,
    });
  }

  let response;
  try {
    response = await fetch(`${API_URL}${path}`, {
      ...options,
      headers: { ...options.headers, Authorization: `Bearer ${session.access_token}` },
    });
  } catch {
    throw new ApiError("Could not reach the backend. Is it running?");
  }

  const payload = await response.json().catch(() => null);
  if (!response.ok || !payload?.success) {
    throw new ApiError(payload?.message || `Request failed (HTTP ${response.status}).`, {
      errorCode: payload?.error_code,
      status: response.status,
    });
  }
  return payload.data;
}

function mapPagination(p) {
  return {
    page: p.page,
    pageSize: p.page_size,
    totalItems: p.total_items,
    totalPages: p.total_pages,
    hasNext: p.has_next,
    hasPrevious: p.has_previous,
  };
}

function mapSession(s) {
  return {
    id: s.id,
    source: s.source,
    status: s.status,
    startedAt: s.started_at,
    endedAt: s.ended_at,
    durationSeconds: s.duration_seconds,
    totalEvents: s.total_events,
    totalAlerts: s.total_alerts,
    yawnCount: s.yawn_count,
    eyeClosureSeconds: s.eye_closure_seconds,
    maxFatigueScore: s.max_fatigue_score,
    finalState: s.final_state,
    alertLevel: s.alert_level,
    createdAt: s.created_at,
  };
}

/**
 * List the signed-in user's monitoring sessions, newest first.
 * @param {{ page?: number, pageSize?: number }} [opts]
 */
export async function listSessions({ page = 1, pageSize = 20 } = {}) {
  const data = await authFetch(`/sessions?page=${page}&page_size=${pageSize}`);
  return { items: data.items.map(mapSession), pagination: mapPagination(data.pagination) };
}

/**
 * Get one session owned by the signed-in user.
 * @param {string} sessionId
 */
export async function getSession(sessionId) {
  const data = await authFetch(`/sessions/${sessionId}`);
  return {
    ...mapSession(data),
    mediaId: data.media_id,
    updatedAt: data.updated_at,
    // `media` is only present once the session has a recording generated by
    // POST /sessions - null for sessions with no stored file.
    media: data.media
      ? {
          bucket: data.media.bucket,
          storagePath: data.media.storage_path,
          mimeType: data.media.mime_type,
        }
      : null,
  };
}

/**
 * Permanently delete one session owned by the signed-in user - its detection
 * events, its linked recording, and the session row itself.
 * @param {string} sessionId
 */
export async function deleteSession(sessionId) {
  await authFetch(`/sessions/${sessionId}`, { method: "DELETE" });
}

/**
 * List one session's detection events (the frame-by-frame timeline), oldest first.
 * @param {string} sessionId
 * @param {{ page?: number, pageSize?: number }} [opts]
 */
export async function listSessionEvents(sessionId, { page = 1, pageSize = 100 } = {}) {
  const data = await authFetch(`/sessions/${sessionId}/events?page=${page}&page_size=${pageSize}`);
  return {
    items: data.items.map((e) => ({
      id: e.id,
      ts: e.ts,
      ear: e.ear,
      mar: e.mar,
      headPitch: e.head_pitch,
      headYaw: e.head_yaw,
      headRoll: e.head_roll,
      eyeClosed: e.eye_closed,
      yawning: e.yawning,
      state: e.state,
      fatigueScore: e.fatigue_score,
      alertLevel: e.alert_level,
      detections: (e.detections ?? []).map(mapDetection),
      confidence: e.confidence,
    })),
    pagination: mapPagination(data.pagination),
  };
}

/** Get the trained model's held-out test-set evaluation (precision/recall/mAP/per-class AP). */
export async function getAIPerformance() {
  const data = await authFetch(`/analytics/ai-performance`);
  return {
    checkpoint: data.checkpoint,
    numTestImages: data.num_test_images,
    iouThreshold: data.iou_threshold,
    precision: data.precision,
    recall: data.recall,
    f1: data.f1,
    meanIou: data.mean_iou,
    detectionAccuracy: data.detection_accuracy,
    map50: data.map_50,
    map5095: data.map_50_95,
    apPerClass: data.ap_per_class.map((c) => ({
      label: c.label,
      averagePrecision: c.average_precision,
    })),
  };
}

function mapSessionTotals(t) {
  return {
    totalSessions: t.total_sessions,
    totalAlerts: t.total_alerts,
    totalYawns: t.total_yawns,
    totalEyeClosureSeconds: t.total_eye_closure_seconds,
    avgFatigueScore: t.avg_fatigue_score,
    avgDurationSeconds: t.avg_duration_seconds,
  };
}

function mapEventTotals(t) {
  return {
    totalEvents: t.total_events,
    yawningEvents: t.yawning_events,
    sleepEvents: t.sleep_events,
    avgConfidence: t.avg_confidence,
  };
}

/**
 * Aggregate the signed-in user's own sessions over a lookback window.
 * @param {{ days?: number }} [opts]
 */
export async function getSessionTrends({ days = 14 } = {}) {
  const data = await authFetch(`/analytics/trends?days=${days}`);
  return {
    days: data.days,
    sessionsPerDay: data.sessions_per_day,
    avgFatiguePerDay: data.avg_fatigue_per_day.map((d) => ({
      date: d.date,
      averageFatigueScore: d.average_fatigue_score,
    })),
    eyeClosurePerDay: data.eye_closure_per_day.map((d) => ({
      date: d.date,
      totalEyeClosureSeconds: d.total_eye_closure_seconds,
    })),
    stateDistribution: data.state_distribution,
    current: mapSessionTotals(data.current),
    previous: mapSessionTotals(data.previous),
  };
}

/**
 * Aggregate the signed-in user's own raw detection events over a lookback
 * window: alerts by hour/weekday/heatmap, EAR/MAR by hour, yawning by day,
 * and alert-severity distribution.
 * @param {{ days?: number }} [opts]
 */
export async function getEventTrends({ days = 14 } = {}) {
  const data = await authFetch(`/analytics/event-trends?days=${days}`);
  return {
    days: data.days,
    alertsByHour: data.alerts_by_hour,
    alertsByWeekday: data.alerts_by_weekday,
    alertHeatmap: data.alert_heatmap,
    avgEarMarByHour: data.avg_ear_mar_by_hour.map((h) => ({
      hour: h.hour,
      avgEar: h.avg_ear,
      avgMar: h.avg_mar,
    })),
    yawnCountByDay: data.yawn_count_by_day,
    alertLevelDistribution: data.alert_level_distribution.map((d) => ({
      alertLevel: d.alert_level,
      count: d.count,
    })),
    current: mapEventTotals(data.current),
    previous: mapEventTotals(data.previous),
  };
}

/** Real backend/database/storage/AI-model status, for the System Health panel. */
export async function getSystemHealth() {
  let response;
  try {
    response = await fetch(`${API_URL}/system/health`);
  } catch {
    throw new ApiError("Could not reach the backend. Is it running?");
  }
  const payload = await response.json().catch(() => null);
  if (!response.ok || !payload?.success) {
    throw new ApiError(payload?.message || `Request failed (HTTP ${response.status}).`, {
      errorCode: payload?.error_code,
      status: response.status,
    });
  }
  return payload.data;
}

/** List every registered user with their profile and effective role. Admin only. */
export async function listAdminUsers() {
  const data = await authFetch(`/admin/users`);
  return data.map((u) => ({
    id: u.id,
    email: u.email,
    displayName: u.display_name,
    role: u.role,
    createdAt: u.created_at,
    lastSignInAt: u.last_sign_in_at,
  }));
}

function mapModelCheckpoint(c) {
  return {
    id: c.id,
    filename: c.filename,
    directory: c.directory,
    sizeBytes: c.size_bytes,
    modifiedAt: c.modified_at,
    compatible: c.compatible,
    incompatibleReason: c.incompatible_reason,
    active: c.active,
  };
}

/**
 * List every real .pth checkpoint under the backend's configured checkpoints
 * directory, each real-load-tested against the current architecture. Admin
 * only. Not instant - every checkpoint is actually loaded once to verify it.
 */
export async function listModelCheckpoints() {
  const data = await authFetch(`/admin/models`);
  return data.map(mapModelCheckpoint);
}

/**
 * Make one real checkpoint the active model for every user of the system.
 * In-memory only for this process - a restart falls back to the
 * server-configured default. Admin only.
 * @param {string} id
 */
export async function activateModelCheckpoint(id) {
  const data = await authFetch(`/admin/models/activate`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ id }),
  });
  return data.map(mapModelCheckpoint);
}

/**
 * Get the currently active model's real metadata (architecture, device,
 * class count, confidence threshold). Admin only.
 */
export async function getActiveModel() {
  const data = await authFetch(`/admin/models/active`);
  return {
    architecture: data.architecture,
    device: data.device,
    numClasses: data.num_classes,
    scoreThreshold: data.score_threshold,
  };
}

/**
 * Rebuild the active checkpoint at a new minimum detection score. The
 * threshold is baked into the network at construction time, so this reloads
 * the model - in-memory only, resets to MODEL_SCORE_THRESHOLD on restart.
 * Admin only.
 * @param {number} scoreThreshold In [0, 1].
 */
export async function setConfidenceThreshold(scoreThreshold) {
  const data = await authFetch(`/admin/models/threshold`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ score_threshold: scoreThreshold }),
  });
  return {
    architecture: data.architecture,
    device: data.device,
    numClasses: data.num_classes,
    scoreThreshold: data.score_threshold,
  };
}

/**
 * Rebuild the active checkpoint targeting a new compute backend. A "gpu"
 * request always succeeds - it picks the best GPU execution provider
 * actually available on the server host and falls back to CPU silently when
 * none is (e.g. in production, which has no GPU at all); compare the
 * returned `device` against what was requested to tell a real switch from a
 * fallback. In-memory only, resets to MODEL_DEVICE on restart. Admin only.
 * @param {"cpu" | "gpu"} device
 */
export async function setComputeDevice(device) {
  const data = await authFetch(`/admin/models/device`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ device }),
  });
  return {
    architecture: data.architecture,
    device: data.device,
    numClasses: data.num_classes,
    scoreThreshold: data.score_threshold,
  };
}

/**
 * Run drowsiness detection on a single image file.
 * @param {File} file
 * @returns {Promise<{
 *   driverState: string, alertLevel: string, fatigueScore: number,
 *   detections: Array<{ label: string, labelIndex: number, score: number, box: { x1:number,y1:number,x2:number,y2:number } }>,
 *   metrics: { eyeAspectRatio: number|null, mouthAspectRatio: number|null, eyesClosed: boolean, yawning: boolean },
 *   inferenceMs: number, imageWidth: number, imageHeight: number,
 * }>}
 */
export async function analyzeImage(file) {
  const body = new FormData();
  body.append("file", file);

  let response;
  try {
    response = await fetch(`${API_URL}/analysis/image`, { method: "POST", body });
  } catch {
    throw new ApiError("Could not reach the analysis service. Is the backend running?");
  }

  const payload = await response.json().catch(() => null);
  if (!response.ok || !payload?.success) {
    throw new ApiError(payload?.message || `Analysis failed (HTTP ${response.status}).`, {
      errorCode: payload?.error_code,
      status: response.status,
    });
  }

  const data = payload.data;
  return {
    driverState: data.driver_state,
    alertLevel: data.alert_level,
    fatigueScore: data.fatigue_score,
    detections: data.detections.map((det) => ({
      label: det.label,
      labelIndex: det.label_index,
      score: det.score,
      box: det.box,
    })),
    metrics: {
      eyeAspectRatio: data.metrics.eye_aspect_ratio,
      mouthAspectRatio: data.metrics.mouth_aspect_ratio,
      eyesClosed: data.metrics.eyes_closed,
      yawning: data.metrics.yawning,
    },
    inferenceMs: data.inference_ms,
    imageWidth: data.image_width,
    imageHeight: data.image_height,
  };
}

function mapDetection(det) {
  return { label: det.label, labelIndex: det.label_index, score: det.score, box: det.box };
}

/**
 * Run drowsiness detection on an uploaded video by sampling frames through
 * the same detector used for images. The backend decides the sample rate
 * actually used (it may differ from `sampleRate`, e.g. for a long clip) and
 * every field below reflects what was actually analysed.
 * @param {File} file
 * @param {number} [sampleRate] Requested samples per second.
 */
export async function analyzeVideo(file, sampleRate = 2) {
  const body = new FormData();
  body.append("file", file);
  body.append("sample_rate", String(sampleRate));

  let response;
  try {
    response = await fetch(`${API_URL}/analysis/video`, { method: "POST", body });
  } catch {
    throw new ApiError("Could not reach the analysis service. Is the backend running?");
  }

  const payload = await response.json().catch(() => null);
  if (!response.ok || !payload?.success) {
    throw new ApiError(payload?.message || `Analysis failed (HTTP ${response.status}).`, {
      errorCode: payload?.error_code,
      status: response.status,
    });
  }

  const data = payload.data;
  return {
    videoDurationSec: data.video_duration_sec,
    videoWidth: data.video_width,
    videoHeight: data.video_height,
    sourceFps: data.source_fps,
    sourceFrameCount: data.source_frame_count,
    sampleFps: data.sample_fps,
    sampledFrameCount: data.sampled_frame_count,
    summary: {
      driverState: data.summary.driver_state,
      alertLevel: data.summary.alert_level,
      fatigueScore: data.summary.fatigue_score,
      maxFatigueScore: data.summary.max_fatigue_score,
      totalYawns: data.summary.total_yawns,
      longestEyeClosureSec: data.summary.longest_eye_closure_sec,
      avgEyeAspectRatio: data.summary.avg_eye_aspect_ratio,
      avgMouthAspectRatio: data.summary.avg_mouth_aspect_ratio,
      avgConfidence: data.summary.avg_confidence,
      totalAlerts: data.summary.total_alerts,
      sessionDurationSec: data.summary.session_duration_sec,
    },
    frames: data.frames.map((f) => ({
      t: f.t,
      driverState: f.driver_state,
      alertLevel: f.alert_level,
      fatigueScore: f.fatigue_score,
      eyeAspectRatio: f.eye_aspect_ratio,
      mouthAspectRatio: f.mouth_aspect_ratio,
      confidence: f.confidence,
      detections: f.detections.map(mapDetection),
    })),
    timeline: data.timeline.map((e) => ({ t: e.t, kind: e.kind, label: e.label })),
    distribution: data.distribution.map((d) => ({ state: d.state, count: d.count })),
    // The backend burns real detection boxes + a state/fatigue HUD directly
    // onto every frame and re-encodes to H.264 - a genuine annotated video,
    // not the raw upload. `null` when one wasn't generated (very long clip,
    // or the encoder failed) - never a fabricated link.
    previewUrl: data.preview_video_url ? `${API_URL}${data.preview_video_url}` : null,
  };
}

/**
 * Submit one completed webcam monitoring session: the MediaRecorder
 * recording plus every event collected locally via analyzeImage() during
 * the session. One-shot - there is no separate start/append/finish call.
 * @param {{ events: Array<object>, startedAt: Date, recordingBlob: Blob }} params
 */
export async function completeSession({ events, startedAt, recordingBlob }) {
  const body = new FormData();
  body.append("recording", recordingBlob, "session.webm");
  body.append(
    "events",
    JSON.stringify(
      events.map((e) => ({
        t: e.t,
        ear: e.ear ?? null,
        mar: e.mar ?? null,
        eye_closed: e.eyeClosed,
        yawning: e.yawning,
        state: e.driverState,
        alert_level: e.alertLevel,
        fatigue_score: e.fatigueScore,
        detections: e.detections.map((d) => ({
          label: d.label,
          label_index: d.labelIndex,
          score: d.score,
          box: d.box,
        })),
      })),
    ),
  );
  body.append("started_at", startedAt.toISOString());

  const {
    data: { session },
  } = await supabase.auth.getSession();
  if (!session?.access_token) {
    throw new ApiError("You must be signed in to save a session.", {
      errorCode: "AUTH_REQUIRED",
      status: 401,
    });
  }

  let response;
  try {
    response = await fetch(`${API_URL}/sessions`, {
      method: "POST",
      body,
      headers: { Authorization: `Bearer ${session.access_token}` },
    });
  } catch {
    throw new ApiError("Could not reach the backend. Is it running?");
  }

  const payload = await response.json().catch(() => null);
  if (!response.ok || !payload?.success) {
    throw new ApiError(payload?.message || `Saving the session failed (HTTP ${response.status}).`, {
      errorCode: payload?.error_code,
      status: response.status,
    });
  }
  return mapSession(payload.data);
}

/**
 * Upload a video for one-shot analysis: the backend samples and analyses it
 * exactly like analyzeVideo(), burns the real detections into an annotated
 * copy, stores it, and creates a session so it appears in Detection History.
 * @param {File} file
 * @param {number} [sampleRate] Requested samples per second.
 */
export async function uploadVideo(file, sampleRate = 2) {
  const body = new FormData();
  body.append("file", file);
  body.append("sample_rate", String(sampleRate));
  return mapSession(await authFetch(`/uploads/video`, { method: "POST", body }));
}

/**
 * Upload a still image for one-shot analysis: the backend analyses it
 * exactly like analyzeImage(), burns the real detections into an annotated
 * copy, stores it, and creates a session so it appears in Detection History.
 * @param {File} file
 */
export async function uploadImage(file) {
  const body = new FormData();
  body.append("file", file);
  return mapSession(await authFetch(`/uploads/image`, { method: "POST", body }));
}
